// ─────────────────────────────────────────────────────────────────────────
//  build_cxx/emit_ninja.hxx — print mode: plan → Ninja file.
//
//  This is not a generator phase. There is no configure cache, no
//  regenerate dance, no intermediate state on disk. It's a pure function
//  from the already-computed session to a Ninja-formatted string. Run
//  with:
//
//      ./build.cxx --emit ninja > build.ninja && ninja
//
//  Use it when you want remote exec (sccache-over-ninja), IDE debugger
//  integration, or 10k-file scale. For everything else the built-in
//  executor is faster to invoke and correct-by-construction.
//
//  We use one generic rule `cmd` that just runs a command string with
//  sh -c. No rule per target, no per-compiler specialization. The
//  command strings already contain everything: compiler, flags,
//  depfile emission, output path. Ninja's restat/depfile support still
//  works because we thread `-MD -MF <path>` through for compile steps.
// ─────────────────────────────────────────────────────────────────────────
#pragma once

#include "executor.hxx"
#include "plan.hxx"

#include <cstdio>
#include <string>
#include <string_view>

namespace build {

// Ninja-escape: $ and : and space in paths get '$' prefix.
[[nodiscard]] inline auto ninja_escape(std::string_view s) -> std::string
{
    std::string o;
    o.reserve(s.size());
    for (char c : s) {
        if (c == ' ' || c == ':' || c == '$') o.push_back('$');
        o.push_back(c);
    }
    return o;
}

// Shell-escape a command for `command = sh -c "<cmd>"`. Double-quote the
// payload and backslash-escape the few characters that matter in that
// context: \ " $ `.
[[nodiscard]] inline auto shell_escape(std::string_view s) -> std::string
{
    std::string o;
    o.reserve(s.size() + 8);
    for (char c : s) {
        if (c == '\\' || c == '"' || c == '$' || c == '`') o.push_back('\\');
        o.push_back(c);
    }
    return o;
}

// Emit a Ninja build file equivalent to the current session's plan.
template <typename Session, typename Project>
[[nodiscard]] inline auto emit_ninja(const Session&   ses,
                                     const Project&   project,
                                     std::string_view build_dir)
    -> std::string
{
    std::string out;
    out.reserve(std::size_t{ 8 } * 1024);

    out += "# Generated by build.cxx --emit ninja\n";
    out += "# Regenerate on every build.cxx change. Do not hand-edit.\n";
    out += "ninja_required_version = 1.10\n\n";

    out += "rule cmd\n";
    out += "  command = sh -c \"$c\"\n";
    out += "  description = $desc\n\n";

    out += "rule cmd_dep\n";
    out += "  command = sh -c \"$c\"\n";
    out += "  description = $desc\n";
    out += "  depfile = $d\n";
    out += "  deps = gcc\n\n";

    // Each step is one `build` edge. Implicit deps link link/archive
    // steps to their target's compile outputs, and to dep libraries.
    for (std::size_t i = 0; i < ses.flat_steps.size(); ++i) {
        const auto& s = ses.flat_steps[i];

        out += "build ";
        out += ninja_escape(s.output_path);
        out += ": ";
        out += s.is_compile ? "cmd_dep" : "cmd";

        if (s.is_compile && !s.primary_input.empty()) {
            out += ' ';
            out += ninja_escape(s.primary_input);
        }

        // Implicit deps for link/archive waves: own compile outputs + dep libs.
        if (!s.is_compile) {
            bool first_implicit = true;
            auto add_implicit = [&](std::string_view p) {
                if (first_implicit) { out += " |"; first_implicit = false; }
                out += ' ';
                out += ninja_escape(p);
            };
            for (std::size_t k = 0; k < ses.flat_steps.size(); ++k) {
                const auto& prev = ses.flat_steps[k];
                if (prev.is_compile && prev.label == s.label) {
                    add_implicit(prev.output_path);
                }
            }
            if (const auto* tgt = project.find_target(s.label)) {
                for (auto dep_name : tgt->dependencies_) {
                    if (const auto* dep = project.find_target(dep_name)) {
                        std::string libpath;
                        libpath.append(build_dir);
                        libpath += "/lib";
                        libpath.append(std::string_view(dep->name_));
                        libpath.append(to_output_ext(dep->kind_));
                        add_implicit(libpath);
                    }
                }
            }
        }
        out += '\n';

        out += "  c = ";
        out += shell_escape(s.command);
        out += '\n';

        out += "  desc = ";
        out += s.is_compile ? "CC   " : "LINK ";
        out += s.label;
        out += ' ';
        out += s.output_path;
        out += '\n';

        if (s.is_compile && !s.depfile_path.empty()) {
            out += "  d = ";
            out += ninja_escape(s.depfile_path);
            out += '\n';
        }
        out += '\n';
    }

    // Default target: build everything.
    if (!ses.flat_steps.empty()) {
        out += "default";
        for (const auto& s : ses.flat_steps) {
            out += ' ';
            out += ninja_escape(s.output_path);
        }
        out += '\n';
    }
    (void) build_dir; // unused for now; reserved if we later move stamps
    return out;
}

} // namespace build
